"""Add blog post schema

Revision ID: c793e120ad
Revises: 1371a0c98ad
Create Date: 2015-05-30 14:32:25.353456

"""

# revision identifiers, used by Alembic.
revision = 'c793e120ad'
down_revision = '1371a0c98ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
